# Generated by Django 4.2.5 on 2023-09-21 22:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("AppClinica", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Estudiante",
            new_name="Cliente",
        ),
    ]
