# Generated by Django 4.2.5 on 2023-09-28 23:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("AppClinica", "0002_rename_estudiante_cliente"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profesor",
        ),
    ]
