# Generated by Django 4.2.5 on 2023-09-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AppClinica", "0004_empleado_delete_curso"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombrep", models.CharField(max_length=30)),
                ("fecha", models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name="Entregable",
        ),
    ]
